services:
  mongodb:
    image: mongo:8
    container_name: nederlands-flashcard-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - nederlands-flashcard-net
    volumes:
      - nederlands-flashcard-data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: nederlands-flashcard-mongo-ui
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - nederlands-flashcard-net

volumes:
  nederlands-flashcard-data:

networks:
  nederlands-flashcard-net:
    driver: bridge